"""Framework-agnostic core: types, errors, config, device probing, registries."""

from .config import Settings, get_settings
from .errors import (
    ArchitectureNotFoundError,
    BackendUnavailableError,
    ConfigError,
    ImageTooLargeError,
    InvalidImageError,
    ModelNotFoundError,
    OutOfMemoryError,
    UnsupportedBackendError,
    VisionSRError,
    WeightsCorruptError,
    WeightsNotFoundError,
)
from .registry import ModelRegistry, architectures, models, register_architecture
from .types import (
    Backend,
    ContentType,
    DeviceInfo,
    EnhanceOptions,
    EnhanceResult,
    Image,
    ImageAnalysis,
    ModelRun,
    ModelSpec,
    Precision,
    Task,
    WeightSource,
)

__all__ = [
    "AI_ROOT",
    "ArchitectureNotFoundError",
    "Backend",
    "BackendUnavailableError",
    "ConfigError",
    "ContentType",
    "DeviceInfo",
    "EnhanceOptions",
    "EnhanceResult",
    "Image",
    "ImageAnalysis",
    "ImageTooLargeError",
    "InvalidImageError",
    "ModelNotFoundError",
    "ModelRegistry",
    "ModelRun",
    "ModelSpec",
    "OutOfMemoryError",
    "Precision",
    "Settings",
    "Task",
    "UnsupportedBackendError",
    "VisionSRError",
    "WeightSource",
    "WeightsCorruptError",
    "WeightsNotFoundError",
    "architectures",
    "get_settings",
    "models",
    "register_architecture",
]
